### ISSUE TITLE
起動時にエラー

### ISSUE THREAD

**Issue by ikatyo0702** [zinntikumugai/BitZenyConfigCreator#2]
このツールを使おうと思い、DLして利用しようとした所この様なエラーが発生しました

```
暗号通貨：BitZeny
Webより取得します。
Webより取得しました。

Unhandled Exception: System.AggregateException: One or more errors occurred. (Re
sponse status code does not indicate success: 404 (Not Found).) ---> System.Net.
Http.HttpRequestException: Response status code does not indicate success: 404 (
Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.<GetStringAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at BitZenyConfigCreator.Program.<WebGet>d__10.MoveNext() in F:\DATA\Programmi
ng\Project\BitZenyConfigCreator\BitZenyConfigCreator\Program.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at BitZenyConfigCreator.Program.<GetWebJson>d__9.MoveNext() in F:\DATA\Progra
mming\Project\BitZenyConfigCreator\BitZenyConfigCreator\Program.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at BitZenyConfigCreator.Program.<MainAsync>d__4.MoveNext() in F:\DATA\Program
ming\Project\BitZenyConfigCreator\BitZenyConfigCreator\Program.cs:line 42
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at BitZenyConfigCreator.Program.Main(String[] args) in F:\DATA\Programming\Pr
oject\BitZenyConfigCreator\BitZenyConfigCreator\Program.cs:line 28
```
一度Wallet本体を起動して、フォルダを作成させている状態です。
これは私の環境上でのみの問題なのか、もしくはこのソフト側が問題なのか分からないのでissueを建てさせて頂きます。お手数をお掛けしますが確認の方を宜しくお願いします。

**Comment by zinntikumugai** [comment]
確認したところ、別のサービスを用意しているときに誤ってサーバーのデータを削除してしまいました
現在は復元済み、こちらでの確認では取得できました
お騒がせしてすいません(ち´；ω；｀)ぇ

**Comment by zinntikumugai** [comment]
合わせて、[BitZeny Wallet Core 2.0.0](https://github.com/BitzenyCoreDevelopers/bitzeny)では初期取得時のサーバーのアドレスを修正されいるためこの`BitZenyConfigCreator`は使わなくても同期できます
今後 __2.0.0以降でないと取引できない__ 等ありますのでもし1.x系を使っている場合は2.x系に移行も合わせてお願いします

**Comment by ikatyo0702** [comment]
2.0.0では使わなくてもいけるんですか...初めて知りました...
メインの方を移行したのですが、メインのHDDが調子が悪くデータ吹っ飛んだら最悪だったので一度別のPCにウォレットの移行を行う作業中の事でしたので...お手数お掛けしました<m(__)m>
